version: '2'

services:

  mbsync:
    build: mbsync
    image: arecker/mbsync:latest
    container_name: mbsync
    network_mode: bridge
    restart: always
    volumes:
      - maildir:/home/mailman/Maildir
    env_file:
      - ~/.mailman.env

  dovecot:
    build: dovecot
    image: arecker/dovecot:latest
    container_name: dovecot
    network_mode: bridge
    restart: always
    ports:
      - 127.0.0.1:143:143
    volumes:
      - maildir:/home/mailman/Maildir

volumes:
  maildir: {}
